# Generated by Django 5.1.1 on 2024-11-04 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_remove_group_members_group_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='pending_approvals',
            field=models.ManyToManyField(blank=True, related_name='pending_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
    ]
